### PR TITLE
Fixes #12, #13, #14

### LINKED ISSUE #12: Panic for invalid keys
If invalid (but base64 decodable) encryption keys are provided, sharedSecret method panics. Now, this can happen in 2 sceneraios:

1) Developer specifies invalid keys (which is not very exceptional)
2) PushSubscription contains invalid encryption keys (which shouldn't happen much)

Should the panic be resolved in the encryption library since the developers specifying bad input seems more likely?

### PR DESCRIPTION
**Pull request by wibblymat**
R: @gauntface @crhym3 
CC: @pinarx

### CODE REVIEW

File: webpush/encrypt.go [hunk 1]
```diff
@@ -250,15 +262,14 @@ func newInfo(infoType string, context []byte) []byte {
...
 //
 // See https://www.rfc-editor.org/rfc/rfc5869.txt
-func hkdf(salt, ikm, info []byte, length int) []byte {
+func hkdf(salt, ikm, info []byte, length int) ([]byte, error) {
 	// HMAC length for SHA256 is 32 bytes, so that is the maximum result length.
-	// HKDF defines a way to have longer lengths, but our partial implementation
-	// will just truncate the result.
 	if length > 32 {
-		length = 32
+		return nil, fmt.Errorf("Can only produce HKDF outputs up to 32 bytes long")
```
Comment (x1ddos) [inline webpush/encrypt.go]: how about handling length > 32. is this the only way? what really happens if length is > 32.

Comment (x1ddos) [inline webpush/encrypt.go]: also, I'm not sure I understand. `hkdf` is unexported so you're in total control what length to provide. why do you even need to return an error? seems an unnecessary complication.

Comment (wibblymat) [inline webpush/encrypt.go]: So, "real" HKDF supports much longer output lengths, but since web push never needs those lengths we can simplify to the version we have here.

If you request a length of, say, 48 bytes and we don't reject that then the current function tries to return the first 48 bytes of a 32 byte array.

As you point out, we control all the callers and they definitely don't request longer outputs. Would you prefer that we just let this function cause a panic? I'm not really bothered either way, I just think that the current truncation could lead to us accidentally introducing a bug in the future. If the spec changes to require 48 byte keys then truncating might not fail obviously, whereas an error will be spotted.

Comment (x1ddos) [inline webpush/encrypt.go]: I think in this case it shouldn't do either. Certainly not panic, nor should it limit length since all callers are internal, you know exactly what you're doing. There's no point in setting foolproof guards against yourself, there are tests for this :)

If an internal call to `hkdf()` depends on some user input, then the caller of hkdf should verify that user input and return an error straight away if needed, without even calling hkdf.

File: webpush/encrypt.go [hunk 2]
```diff
@@ -270,7 +281,7 @@ func hkdf(salt, ikm, info []byte, length int) []byte {
 	mac = hmac.New(sha256.New, prk)
 	mac.Write(info)
 	mac.Write([]byte{1})
-	return mac.Sum(nil)[0:length]
+	return mac.Sum(nil)[0:length], nil
```
Comment (x1ddos) [inline webpush/encrypt.go]: I'd say this is the only place where you want to verify length is not > than `len(mac.Sum(nil))` but only to avoid panic.

Comment (x1ddos) [inline webpush/encrypt.go]: e.g.

``` go
b := mac.Sum(nil)
n := len(b)
if length > n {
  length = n
}
return b[:n]
```

Comment (wibblymat) [inline webpush/encrypt.go]: As currently written, `len(b)` is always 32, because it is a SHA256 hash. Your code is functionally equivalent to the current code, although a little more future proof.

Right now we have three options for what `hkdf` should do with a high length
1. panic
2. error (proposed behaviour)
3. silently return an incorrect result (current behaviour)

None of these things can **actually** happen right now because the lengths are hard coded at each call site. However, it came up in security review that it would be appropriate to code defensively, and 3 is the only actually dangerous option.

Comment (x1ddos) [inline webpush/encrypt.go]: True, missed the fact that it's SHA256. In which case I understand the issue even less now. What's the problem here when you know exactly the max length and you control all the callers to the function where length is hardcoded.

How can there be "If the length requested is more than 32 ..." in #14 when using SHA256?

Comment (wibblymat) [inline webpush/encrypt.go]: What this function does is create a SHA256 hash of some data and then return the first `length` bytes of it. Because a SHA256 hash is 32 bytes long, a requested `length` of > 32 will fail.

The actual lengths used by web push are [32](https://github.com/GoogleChrome/push-encryption-go/blob/master/webpush/encrypt.go#L177), [16](https://github.com/GoogleChrome/push-encryption-go/blob/master/webpush/encrypt.go#L196) and [12](https://github.com/GoogleChrome/push-encryption-go/blob/master/webpush/encrypt.go#L201).

If a future version of the spec requires some value to be created with an HKDF length of more than 32, I really think that it is better to fail obviously (big error, length was too big) than fail subtly (everything seemed to work but the client rejected the push message). The internal security audit of this code had this as a suggestion, which is where the issue came from.

However, I also want to get the rest merged so if I haven't convinced you yet then I'll do whatever you think best from here :)

Comment (x1ddos) [inline webpush/encrypt.go]: Ok, to get to some compromise, between returning an error and panic, I would suggest panic since all callers of `hkdf` are internal and the `length` is not actually expected to be above 32 bits.

This will also eliminate `error` as the second return value introduced in this change and put back most of func signatures as they were before. 

Do you want to change this and then I'll review the rest of the code? It would be easier to see what actually chagned.

**Comment by wibblymat** [comment]
@crhym3 whoops, pushed the commit but forgot to say "PTAL"

File: webpush/encrypt_test.go [hunk 3]
```diff
@@ -135,19 +139,78 @@ func TestEncrypt(t *testing.T) {
...
+	if err != nil {
+		t.Error(err)
+	}
+
+	expCiphertext, err := b64.DecodeString(rfcCipher)
+	if err != nil {
+		t.Error(err)
+	}
+	if !bytes.Equal(result.Ciphertext, expCiphertext) {
+		t.Errorf("Expected ciphertext to be %v, got %v", result.Ciphertext, expCiphertext)
```
Comment (x1ddos) [inline webpush/encrypt_test.go]: it's usually the other way around: "have = ...; want ..."

File: webpush/encrypt.go [hunk 4]
```diff
@@ -296,8 +298,11 @@ func encrypt(plaintext, key, nonce []byte) ([]byte, error) {
 
 // Given the coordinates of a party A's public key and the bytes of party B's
 // private key, compute a shared secret.
-func sharedSecret(curve elliptic.Curve, pub, priv []byte) []byte {
+func sharedSecret(curve elliptic.Curve, pub, priv []byte) ([]byte, error) {
 	publicX, publicY := elliptic.Unmarshal(curve, pub)
+	if publicX == nil {
+		return nil, fmt.Errorf("Invalid keys provided")
```
Comment (x1ddos) [inline webpush/encrypt.go]: I would provide a bit more info. "invalid keys" can be anything and quite unhelpful. you're expecting a certain component of the key to be present and can just say so in the error.

**Comment by x1ddos** [comment]
Sorry, should've looked at it sooner.
It's much better now! Just a couple nits but I'm really glad there's no change in exported functions.

File: webpush/encrypt_test.go (hunk 3 above)
Comment (wibblymat) [inline webpush/encrypt_test.go]: Not sure what you mean. Is this about the wording of the error? Something like "Ciphertext: have: %v, want: %v"?

Comment (x1ddos) [inline webpush/encrypt_test.go]: Well, it's not just the wording: arguments are typically reversed. First is what you have (actual), second is what you want (expected).

It's also not clear to me which is which: I suspect `expCiphertext` is expected cipher but, for some reason, it is printed as actual result. I think there's some confusion here.

**Comment by wibblymat** [comment]
Ok, PTAL. I'd made the same mistake with the expected/actual values being flipped in a bunch of other places, too.

**Comment by x1ddos** [comment]
LGTM
